collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 1
color:
  saturation: 1
  brandStrength: 0.4957035
  lightness: 1
  brandColors:
    - '#4C5C5C'
    - '#FFFFFB'
    - '#9B999A'
    - '#FF8853'
    - '#FFCF78'
  rhythmicContrast: 1
layout_spectrum: 0.9492195
name: 'Yes!'
